### ISSUE TITLE
[bug] For non-numeric during deposit Gas, the sign is sent.

### ISSUE THREAD

**Issue by litang1006** [syslink/quarkchain-auction#11]
For User Gas Reserve, when input non- numeric, then sign page can pop up and sign successfully. The transaction is sent.
![Screen Shot 2020-04-21 at 4 01 16 PM](https://user-images.githubusercontent.com/44258843/79841233-b5dd0180-83e9-11ea-8166-d1b19afad89f.png)

**Comment by syslink** [comment]
priority: 3

**Comment by syslink** [comment]
fixed, please check it.

**Comment by litang1006** [comment]
not fixed. can sign success. 
![Screen Shot 2020-04-23 at 10 41 40 AM](https://user-images.githubusercontent.com/44258843/80053281-1d609180-854f-11ea-8f01-dfc602d9c314.png)

**Comment by syslink** [comment]
![image](https://user-images.githubusercontent.com/3832817/80089023-e5c60980-858f-11ea-9019-dacdf7d45aa2.png)
Can test it on http://quarkauction.xchainunion.com/.

**Comment by litang1006** [comment]
test on http://quarkauction.xchainunion.com/. fixed
